vpc_cidr_block: "{{ cidr_block[environ] }}"

vpc_resource_tags: { "Name": "bastion", "group": "gaia", "env": "{{ environ }}"}

vpc_subnets:
  # public subnets
  - cidr: "{{ subnet_cidr.public.first[environ] }}"
    az: "{{ ec2_region_az1 }}"
    resource_tags: { "Name": "bastion-public-1", "env": "{{ environ }}", "group": "gaia", "tier": "public"}
  - cidr: "{{ subnet_cidr.public.second[environ] }}"
    az: "{{ ec2_region_az2 }}"
    resource_tags: { "Name": "bastion-public-2", "env": "{{ environ }}", "group": "gaia", "tier": "public"}
  # private subnets
  - cidr: "{{ subnet_cidr.private.first[environ] }}"
    az: "{{ ec2_region_az1 }}"
    resource_tags: { "Name": "bastion-private-1", "env": "{{ environ }}", "group": "gaia", "tier": "private"}
  - cidr: "{{ subnet_cidr.private.second[environ] }}"
    az: "{{ ec2_region_az2 }}"
    resource_tags: { "Name": "bastion-private-2", "env": "{{ environ }}", "group": "gaia", "tier": "private"}

vpc_internet_gateway: "yes"

vpc_route_tables_tags: { "Name": "bastion-rt", "env": "{{ environ }}", "group": "gaia" }

vpc_dns_zone: "gaia-{{ env_nick[environ] }}.{{ ec2_region }}.priv"
