- hosts: tag_Name_Bastion
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all

  tasks:
  # - name: Include the variables specific to the vpc
  #   include_vars: envs/{{ environ| default("prod") }}

  # delete previously create Bastion instances
  - debug: var=ec2_id
  - name: Terminate previously launched Bastion instances
    local_action:
      module: ec2
      ec2_region: "{{ ec2_region }}"
      instance_ids: "{{ ec2_id }}"
      state: absent
    ignore_errors: yes

  # delete previous Bastion VPC
  # - debug: var=ec2_vpc_id
  # - name: Delete previous Bastion VPC with all resource_tags
  #   local_action:
  #     module: ec2_vpc
  #     ec2_region: "{{ ec2_region }}"
  #     cidr_block: "{{ vpc_cidr_block }}"
  #     resource_tags: "{{ vpc_resource_tags }}"
  #     vpc_id: "{{ ec2_vpc_id }}"
  #     state: absent
  #   ignore_errors: yes
