---
- name: Find docker registries and terminate them
  connection: local
  hosts: tag_Name_docker_registry:&tag_env_{{ environ | default("develop") }}:&{{ lookup('env', 'AWS_DEFAULT_REGION') }}
  gather_facts: False
  roles:
    - terminate
