---
# create new group from launced EC2 intances (from autoscale group)
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/bastion.yaml
  vars:
    - bastion_asg_hosts: "{{bastion_asg_group_name}}:&{{ec2_region}}"

  tasks:

  - name: create a new hosts group with public ip for launched instances
    add_host: >
      hostname="{{item}}"
      groupname=launched_bastion
      ansible_ssh_private_key_file=keys/{{ec2_region}}/{{bastion_keypair_file}}
    with_items: groups.{{bastion_asg_group_name}}

  - name: Wait for SSH to come up
    wait_for: host="{{item}}" port=22 delay=20 timeout=320 state=started
    with_items: groups.launched_bastion

# configure bastion instances
- name: Configure created bastion instances
  hosts: launched_bastion
  sudo: True
  roles:
    - role: bastion_configure
