---
#Create and config the VPC
- name: Provision VPC and machines
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all.yaml
  - group_vars/envs/{{ environ | default("production") }}/vpc.yaml
  - group_vars/envs/{{ environ | default("production") }}/bastion.yaml
  roles:
    # generate bastion key pair
    - role: keygen
      keypair_name: "{{ bastion_keypair_name }}"
      keypair_file: "{{ bastion_keypair_file }}"

    # create a new VPC
    - role: vpc

    # create bastion cluster
    - role: bastion

  # configure bastion instances
- name: Configure created bastion instances
  hosts: launched_bastion
  sudo: True
  roles:
    - role: bastion_configure
