docker_registry_security_group:
  name: docker_registry_sg_test
  desc: the security group for the docker-registry vpc
  rules:
    - proto: tcp
      from_port: 5000
      to_port: 5000
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ vpc_cidr_block }}"

docker_registry_keypair_name: docker-registry-keypair-test
docker_registry_keypair_file: docker-registry-key-test.pem

docker_registry_channel: alpha

docker_registry_instance_type: m3.large     # 2 vCPU, 7.5GB RAM, 1x32 SSD

docker_registry_instance_tags: { "Name": "docker-registry", "env": "testing", "group": "gaia", "type": "docker-registry-vm", "decription": "Docker Registry Node" }
