docker_registry_security_group:
  name: docker_registry_sg_prod
  desc: the security group for the docker-registry vpc
  rules:
    - proto: tcp
      from_port: 5443
      to_port: 5443
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ vpc_cidr_block }}"

# size in GB
docker_registry_volume_size: 60

# ssh keypair
docker_registry_keypair_name: docker-registry-keypair-prod
docker_registry_keypair_file: docker-registry-key-prod.pem

# https server certificate
gaia_ca_file: gaia-ca-prod
gaia_ca_subj: "/C=/ST=/L=/O=/CN={{ vpc_dns_zone }}"
docker_registry_cert_file: docker-registry-cert-prod
docker_registry_cert_subj: "/C=/ST=/L=/O=/CN=docker-registry.{{ vpc_dns_zone }}"

docker_registry_channel: alpha
docker_registry_coreos_version: 815.0.0

docker_registry_instance_type: m3.large     # 2 vCPU, 7.5GB RAM, 1x32 SSD - $0.133 per Hour

docker_registry_instance_tags: { "Name": "docker-registry", "env": "production", "group": "gaia", "type": "docker-registry-vm", "decription": "Docker Registry Node" }
