vpc_cidr_block: 10.0.0.0/16

vpc_resource_tags: { "Name": "bastion", "group": "gaia", "env": "production"}

vpc_subnets:
  # public subnets
  - cidr: 10.0.1.0/24
    az: "{{ ec2_region_az1 }}"
    resource_tags: { "Name": "bastion-1", "env": "production", "group": "gaia", "tier": "public"}
  - cidr: 10.0.2.0/24
    az: "{{ ec2_region_az2 }}"
    resource_tags: { "Name": "bastion-2", "env": "production", "group": "gaia", "tier": "public"}

vpc_internet_gateway: "yes"

vpc_route_tables:
  - subnets:
     - 10.0.1.0/24
     - 10.0.2.0/24
    routes:
      - dest: 0.0.0.0/0
        gw: igw
    resource_tags: { "Name": "bastion-rt", "env": "production", "group": "gaia" }
